// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueryHandler.DataAccess;

namespace QueryHandler.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20190102230135_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("QueryHandler.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AuditState");

                    b.Property<string>("AuditType");

                    b.Property<DateTime>("DateCreated");

                    b.HasKey("Id");

                    b.ToTable("Audit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuditState = 0,
                            AuditType = "Default",
                            DateCreated = new DateTime(2019, 1, 2, 23, 1, 35, 52, DateTimeKind.Local).AddTicks(3330)
                        },
                        new
                        {
                            Id = 2,
                            AuditState = 0,
                            AuditType = "section 1",
                            DateCreated = new DateTime(2019, 1, 1, 23, 1, 35, 55, DateTimeKind.Local).AddTicks(180)
                        },
                        new
                        {
                            Id = 3,
                            AuditState = 0,
                            AuditType = "Default",
                            DateCreated = new DateTime(2018, 12, 31, 23, 1, 35, 55, DateTimeKind.Local).AddTicks(210)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
